---

# © Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

- name: Include pgdcli-pre-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/pgdcli-pre-update.yml"
  
- name: Determine if pgdcli version needs to be upgraded
  include_role:
    name: pgdcli/pkg
    tasks_from: check-update.yml

- block:
  - name: Upgrade pgdcli package
    include_role:
      name: pgdcli
      tasks_from: upgrade.yml

  - name: Post upgrade pgdcli info tests
    include_role: 
      name: test
      tasks_from: pgd-cli/info.yml
  when: pgdcli_pkg_check.results != []
