---

# © Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

- package_facts:
    manager: auto

- name: Remove {{ package_name }} package
  package:
    name: "{{ package_name }}"
    state: absent
  when: package_name in ansible_facts.packages